swagger: '2.0'
info:
  title: PetStore Inventory Service API
  description: This API defines the APIs inventory service provided
  version: "1.0"
host: api.petstore.thoughtworks.com
schemes:
  - http
  - https
basePath: /inventory
consumes:
  - application/json
produces:
  - application/json
paths:
  /species:
    get:
      summary: The API to view all species
      description: user wants to view all species
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/species-list-response'
  
  /species/{species_id}/breeds:
    get:
      summary: The API to view all breeds under a species
      description: user wants to view all breeds under a species
      parameters:
        - $ref: '#/parameters/species_id'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/breed-list-response'
        404:
          $ref: '#/responses/error404'
    
  /species/{species_id}/breeds/{breed_id}/pets:
    get:
      summary: The API to view all pets of a breed
      description: user wants to view all pets of a breed
      parameters:
        - $ref: '#/parameters/species_id'
        - $ref: '#/parameters/breed_id'
        - $ref: '#/parameters/curPage'
        - $ref: '#/parameters/pageSize'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/pet-list-response'
        404:
          $ref: '#/responses/error404'
          
  /species/{species_id}/breeds/{breed_id}/pets/{pet_id}:
    get:
      summary: The API to view a pet info
      description: user wants to view details of a specific pet
      parameters:
        - $ref: '#/parameters/species_id'
        - $ref: '#/parameters/breed_id'
        - $ref: '#/parameters/pet_id'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/pet'
        404:
          $ref: '#/responses/error404'
    
parameters:
  species_id:
    name: species_id
    in: path
    type: string
    description: species id
    required: true
    
  breed_id:
    name: breed_id
    in: path
    type: string
    description: breed id
    required: true
   
  pet_id:  
    name: pet_id
    in: path
    type: string
    description: pet id
    required: true
    
  curPage:
    name: curPage
    in: query
    description: current page of record list
    type: integer
    required: false
    
  pageSize:
    name: pageSize
    in: query
    description: the number of record of a page
    type: integer
    required: false
    
responses:
  error404:
    description: Not Found
   
definitions:
  species:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      image_url:
        type: string

  species-list-response:
    type: array
    items:
      $ref: '#/definitions/species'
  
  breed:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      image_url:
        type: string
  
  breed-list-response:
    type: array
    items:
      $ref: '#/definitions/breed'
      
  pet:
    type: object
    properties:
      price:
        type: number
      stock:
        type: integer
      description:
        type: string
      images:
        type: array
        items:
          type: string
      shop:
        type: object
        properties:
          name:
            type: string
          address:
            type: string
          introduction:
            type: string
          phone:
            type: string
          image_url:
            type: string
        
  pet-info:
    type: object
    properties:
      shop_name:
        type: string
      shop_address:
        type: string
      price:
        type: number
      image_url:
        type: string
  
  pet-list-response:
    type: object
    properties:
      meta:
        type: object
        properties:
          current_page:
            type: number
            format: int32
            minimum: 1
          page_size:
            type: number
            format: int32
            minimum: 1
          page_number:
            type: number
            format: int32
            minimum: 1
      pets:
        type: array
        items:
          $ref: '#/definitions/pet-info'